"""empty message

Revision ID: 1075b3c86955
Revises: 59bfd5dfc517
Create Date: 2023-08-20 19:28:08.744512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1075b3c86955'
down_revision = '59bfd5dfc517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_constraint('uq_article_guid', type_='unique')
        batch_op.create_index(batch_op.f('ix_article_guid'), ['guid'], unique=True)
        batch_op.drop_constraint('fk_article_bookmarker_id_user', type_='foreignkey')
        batch_op.drop_column('bookmarker_id')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint('uq_review_guid', type_='unique')
        batch_op.create_index(batch_op.f('ix_review_guid'), ['guid'], unique=True)
        batch_op.drop_constraint('fk_review_bookmarker_id_user', type_='foreignkey')
        batch_op.drop_column('bookmarker_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bookmarker_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_review_bookmarker_id_user', 'user', ['bookmarker_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_review_guid'))
        batch_op.create_unique_constraint('uq_review_guid', ['guid'])

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bookmarker_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_article_bookmarker_id_user', 'user', ['bookmarker_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_article_guid'))
        batch_op.create_unique_constraint('uq_article_guid', ['guid'])

    # ### end Alembic commands ###
