"""empty message

Revision ID: 147966233367
Revises: f35900db15ea
Create Date: 2023-09-03 20:07:34.177681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147966233367'
down_revision = 'f35900db15ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_review',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], name=op.f('fk_user_review_review_id_review')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_review_user_id_user'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_review')
    # ### end Alembic commands ###
