"""empty message

Revision ID: 1c33f5d91d8a
Revises: a7cbd65819ea
Create Date: 2023-08-03 16:17:29.102418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c33f5d91d8a'
down_revision = 'a7cbd65819ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('link', sa.String(length=256), nullable=True),
    sa.Column('pubdate', sa.DateTime(), nullable=True),
    sa.Column('guid', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid'),
    sa.UniqueConstraint('link')
    )
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_index('ix_article_link')
        batch_op.drop_index('ix_article_title')

    op.drop_table('article')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), nullable=True),
    sa.Column('link', sa.VARCHAR(length=256), nullable=True),
    sa.Column('desc', sa.VARCHAR(length=512), nullable=True),
    sa.Column('pubdate', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.create_index('ix_article_title', ['title'], unique=False)
        batch_op.create_index('ix_article_link', ['link'], unique=False)

    op.drop_table('review')
    # ### end Alembic commands ###
