"""empty message

Revision ID: 1dd2fb6801bb
Revises: 
Create Date: 2023-08-20 20:21:19.458816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dd2fb6801bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('link', sa.String(length=256), nullable=True),
    sa.Column('pubdate', sa.DateTime(), nullable=True),
    sa.Column('guid', sa.String(length=256), nullable=True),
    sa.Column('source', sa.String(length=218), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article')),
    sa.UniqueConstraint('link', name=op.f('uq_article_link'))
    )
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_guid'), ['guid'], unique=True)
        batch_op.create_index(batch_op.f('ix_article_pubdate'), ['pubdate'], unique=False)

    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('link', sa.String(length=256), nullable=True),
    sa.Column('pubdate', sa.DateTime(), nullable=True),
    sa.Column('guid', sa.String(length=256), nullable=True),
    sa.Column('source', sa.String(length=218), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review')),
    sa.UniqueConstraint('link', name=op.f('uq_review_link'))
    )
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_guid'), ['guid'], unique=True)
        batch_op.create_index(batch_op.f('ix_review_pubdate'), ['pubdate'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_pubdate'))
        batch_op.drop_index(batch_op.f('ix_review_guid'))

    op.drop_table('review')
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_pubdate'))
        batch_op.drop_index(batch_op.f('ix_article_guid'))

    op.drop_table('article')
    # ### end Alembic commands ###
