"""empty message

Revision ID: 32915bf105bb
Revises: 54f713b62eab
Create Date: 2023-07-26 21:56:44.891684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32915bf105bb'
down_revision = '54f713b62eab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=32), nullable=True))
        batch_op.drop_column('source')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.VARCHAR(length=32), nullable=True))
        batch_op.drop_column('author')

    # ### end Alembic commands ###
