"""empty message

Revision ID: 51f8d841d613
Revises: 147966233367
Create Date: 2023-09-23 01:52:38.126772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51f8d841d613'
down_revision = '147966233367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('author')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=128), nullable=True))

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=128), nullable=True))

    # ### end Alembic commands ###
