"""empty message

Revision ID: 54f713b62eab
Revises: 
Create Date: 2023-07-26 21:44:40.358347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54f713b62eab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('link', sa.String(length=256), nullable=True),
    sa.Column('desc', sa.String(length=512), nullable=True),
    sa.Column('pubdate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_link'), ['link'], unique=True)
        batch_op.create_index(batch_op.f('ix_article_title'), ['title'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_title'))
        batch_op.drop_index(batch_op.f('ix_article_link'))

    op.drop_table('article')
    # ### end Alembic commands ###
