"""empty message

Revision ID: a23a1d58e892
Revises: b25ae3dc3de6
Create Date: 2023-08-08 16:04:41.687430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a23a1d58e892'
down_revision = 'b25ae3dc3de6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=218), nullable=True))

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=218), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('source')

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
