"""empty message

Revision ID: a7cbd65819ea
Revises: 32915bf105bb
Create Date: 2023-07-26 22:06:16.527921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7cbd65819ea'
down_revision = '32915bf105bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=32), nullable=True))

    # ### end Alembic commands ###
