"""empty message

Revision ID: b25ae3dc3de6
Revises: 2b8a4a2af1ee
Create Date: 2023-08-07 21:48:05.947238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b25ae3dc3de6'
down_revision = '2b8a4a2af1ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=128), nullable=True))

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('author')

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('author')

    # ### end Alembic commands ###
